### ISSUE TITLE
What about shiro-go

### ISSUE THREAD

**Issue by muei** [mikespook/gorbac#10]
I suggest that we can learn from the `java`'s `shiro` framework.  
http://shiro-go.googlecode.com

**Comment by mikespook** [comment]
Shiro is a security framework and designed to be powerful and easy-to-use, which means it has several components serving different functions. 
But the goRBAC intends to be an authorization library, no authentication, no session management, or others. 

Anyway, goRBAC could be integrated into a framework for the authorization function. I think it would be a framework exporting some go interfaces. All we need is an adapter which fits those interfaces to combine goRBAC into the security framework.

I will think about it later.

**Comment by mikespook** [comment]
Less is more. So don't want any complex thing here. Closed
