### ISSUE TITLE
How to add more permissions to a role?

### ISSUE THREAD

**Issue by xpbliss** [mikespook/gorbac#12]
How to add more permissions to a role?

**Comment by mikespook** [comment]
`[Role](https://godoc.org/github.com/mikespook/gorbac#Role)` is an interface which has a method named `AddPermission`. You can call this method multi times to set varies `Permission` (s).

You can see how it works in the [test case](https://github.com/mikespook/gorbac/blob/master/rbac_test.go#L26) of  `[StdRole.AddPermission](https://godoc.org/github.com/mikespook/gorbac#StdRole.AddPermission)`.
