### ISSUE TITLE
Is there any storage backend support? e.g. mongo. redis.

### ISSUE THREAD

**Issue by guijun** [mikespook/gorbac#13]
Is there any storage backend support? e.g. mongo. redis.

**Comment by mikespook** [comment]
No! You have to implement UI, storage & some sort of details by yourself. Eg., if you need more fine control permissions and storing extra data into `Role`, following the interfaces to implement your own `Role` & `Permission` is the best way. 

This package is intended to be a lightweight, easy-using library, and focus on permission controlling itself. So, it won't cover all layers in your application. You can find more information about the idea in [this post](https://blog.8thlight.com/uncle-bob/2012/08/13/the-clean-architecture.html) written by Uncle Bob.
