### ISSUE TITLE
Role Interface is way outdated

### ISSUE THREAD

**Issue by t0il3ts0ap** [mikespook/gorbac#23]
```
type Role interface {
	ID() string
	Permit(Permission) bool
}
```

This Interface should list all the methods `StdRole` struct has, otherwise we have to keep on doing typecasting. 
For example https://godoc.org/github.com/mikespook/gorbac#RBAC.Get method returns object of type `Role`. If you want to assign a permission to it, you have to first typecast to `StdRole`, as `func Assign(...)` is not listed in the above mentioned interface

I feel this related issue was wrong closed https://github.com/mikespook/gorbac/issues/12

**Comment by mikespook** [comment]
The Role interface is a minimal set of methods a role needs.
While StdRole is an implement struct. Therefore, the methods which are not in the Role interface can be named/implemented difference.

In most of the case, StdRole has enough functions to be used. But sometimes, you may want to implement your own `Role` instance.

And yes, typecast is inconvenient. But that's the best position we can get before we have a generic way.
