### ISSUE TITLE
Error handling now done correctly

### ISSUE THREAD

**Issue by virajindasrao** [mikespook/gorbac#27]
https://github.com/mikespook/gorbac/blob/a989d0e80a235460ebe9e8f2e7971e9ed948db88/permission.go#L32

api:runtime error: invalid memory address or nil pointer dereference
github.com/mikespook/gorbac/permission.go:33
github.com/mikespook/gorbac/role.go:53
github.com/mikespook/gorbac/rbac.go:199
github.com/mikespook/gorbac/rbac.go:194
github.com/mikespook/gorbac/helper.go:78

**Comment by virajindasrao** [comment]
opening another issue

**Comment by mikespook** [comment]
Could you give me more details?
