### ISSUE TITLE
Support returning error to AddPermission

### ISSUE THREAD

**Issue by euforia** [mikespook/gorbac#9]
I have a particular use case where errors may be introduced when performing an `AddPermission`.  I would like to propose a list change to the interface from `AddPermission(string)` to `AddPermission(string) error`.  Any thoughts?

**Comment by mikespook** [comment]
I will put this change to the branch [redesign](https://github.com/mikespook/gorbac/tree/redesign). It takes a while, but now I have time to continue the work.

**Comment by mikespook** [comment]
The interface has already changed to [AddPermission(string) error](https://github.com/mikespook/gorbac/blob/master/role.go#L44)
